//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltaMedica
    {
        public int idAltaMedica { get; set; }
        public int idIngreso { get; set; }
        public Nullable<int> idHabitacion { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Ingresos Ingresos { get; set; }
    }
}
